import React from 'react';

export default function AIActModal({ agent, onClose }) {
  const risk = agent.compliance?.risk_level || "Low";
  const riskStyle = risk === "Low" ? "text-emerald-700 border-emerald-200 bg-emerald-50"
    : risk === "Medium" ? "text-amber-700 border-amber-200 bg-amber-50"
    : "text-rose-700 border-rose-200 bg-rose-50";

  const exportPDF = () => {
    const win = window.open('', '_blank');
    win.document.write(`<html><head><title>AI Act Compliance — ${agent.name}</title>
    <style>body{font-family:Georgia,serif;padding:48px;max-width:640px;margin:0 auto;color:#1e293b}h1{font-size:28px;margin-bottom:4px}h2{font-size:18px;color:#64748b;font-weight:normal;margin-bottom:32px}table{width:100%;border-collapse:collapse}td{padding:12px 8px;border-bottom:1px solid #e2e8f0;font-size:15px}td:first-child{color:#64748b;width:45%}.badge{display:inline-block;padding:6px 16px;border-radius:999px;font-size:13px;font-weight:bold;margin-bottom:24px}.low{background:#f0fdf4;color:#166534;border:1px solid #bbf7d0}.medium{background:#fffbeb;color:#92400e;border:1px solid #fde68a}.footer{margin-top:48px;font-size:12px;color:#94a3b8;border-top:1px solid #e2e8f0;padding-top:16px}</style>
    </head><body>
    <h1>EU AI Act Compliance Card</h1><h2>${agent.name} · ${agent.role}</h2>
    <div class="badge ${risk.toLowerCase()}">${risk} Risk</div>
    <table>
      <tr><td>Underlying Model</td><td><strong>${agent.compliance?.underlying_model}</strong></td></tr>
      <tr><td>Data Processed</td><td><strong>${agent.compliance?.data_processed}</strong></td></tr>
      <tr><td>EU Data Residency</td><td><strong>${agent.compliance?.eu_data_residency ? '✅ Confirmed' : '❌ Not guaranteed'}</strong></td></tr>
      <tr><td>Audit Log</td><td><strong>${agent.compliance?.audit_log ? '✅ Full audit trail' : '❌ Not available'}</strong></td></tr>
      <tr><td>Exportable Compliance Doc</td><td><strong>✅ Generated on demand</strong></td></tr>
    </table>
    <div class="footer">Generated by Bottega · Infrastructure: Vultr EU · ${new Date().toLocaleDateString('en-GB', {day:'numeric',month:'long',year:'numeric'})}</div>
    </body></html>`);
    win.document.close();
    setTimeout(() => win.print(), 300);
  };

  return (
    <div className="fixed inset-0 z-50 modal-backdrop flex items-center justify-center p-4" onClick={onClose}>
      <div className="bg-white border border-slate-200 rounded-[2rem] p-8 max-w-md w-full shadow-[0_30px_60px_-10px_rgba(0,0,0,0.25)] animate-fade-in-up" onClick={e => e.stopPropagation()}>
        <div className="flex items-start justify-between mb-6">
          <div>
            <div className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-1">EU AI Act Compliance Card</div>
            <h3 className="text-2xl font-display font-bold text-slate-900">{agent.name}</h3>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-700 text-2xl leading-none">&times;</button>
        </div>
        <div className={`inline-flex items-center gap-2 px-4 py-2 rounded-full border text-sm font-bold mb-6 ${riskStyle}`}>
          <span className="w-2 h-2 rounded-full bg-current" />Risk Level: {risk}
        </div>
        <div className="space-y-3 mb-6">
          {[
            ["Underlying Model", agent.compliance?.underlying_model],
            ["Data Processed", agent.compliance?.data_processed],
            ["EU Data Residency", agent.compliance?.eu_data_residency ? "✅ Confirmed" : "❌ Not guaranteed"],
            ["Audit Log", agent.compliance?.audit_log ? "✅ Full audit trail" : "❌ Not available"],
            ["Exportable Compliance Doc", "✅ PDF + CSV audit log"],
          ].map(([label, value]) => (
            <div key={label} className="flex items-start justify-between gap-4 py-2 border-b border-slate-100">
              <span className="text-sm text-slate-500 font-medium shrink-0">{label}</span>
              <span className="text-sm text-slate-900 font-semibold text-right">{value}</span>
            </div>
          ))}
        </div>
        <div className="flex items-center justify-between pt-2">
          <div className="flex items-center gap-2">
            <div className="w-5 h-5 bg-[#1a1a2e] rounded flex items-center justify-center"><span className="text-[9px] font-bold text-blue-400">V</span></div>
            <span className="text-xs text-slate-400">Infrastructure: Vultr EU</span>
          </div>
          <button onClick={exportPDF} className="text-xs bg-slate-900 text-white px-4 py-2 rounded-full font-bold hover:bg-emerald-600 transition-all">Export PDF</button>
        </div>
      </div>
    </div>
  );
}
